#!/usr/bin/env php
<?php

/**
 * @param $text string Текст сообщения
 * @return array Список ошибок
 */

require_once __DIR__ . '/src/check.php';

if (!@$argv[1]) {
    $path = trim(`which commit-message-check`);
    echo <<<HELP
Для того чтобы создать глобальную папку с конфигурацией git выполните
mkdir -p ~/.git_template/hooks && git config --global init.templatedir '~/.git_template'
Теперь зарегистрируйте хук в глобальном шаблоне
ln -s {$path} ~/.git_template/hooks/commit-msg
Либо зарегистрируйте только локально
ln -s {$path} .git/hooks/commit-msg
HELP;

    exit(1);
}

$errors = check(file_get_contents($argv[1]));

if (count($errors)) {
    echo implode(PHP_EOL, array_keys($errors)), PHP_EOL;
    exit(1);
}

exit(0);
