#!/usr/bin/env php
<?php

require_once __DIR__ . '/src/commit_message_check.php';

if (!@$argv[1]) {
    $path = trim(`which commit-message-check`);
    $HELP = <<<HELP
Для того чтобы создать глобальную папку с конфигурацией git выполните
mkdir -p ~/.git_template/hooks && git config --global init.templatedir '~/.git_template'
И зарегистрируйте хук в глобальном шаблоне
ln -s {$path} ~/.git_template/hooks/commit-msg

Либо зарегистрируйте только локально для текущего репозитория
ln -s {$path} .git/hooks/commit-msg
HELP;
    echo $HELP;
    exit(1);
}

$errors = commit_message_check(file_get_contents($argv[1]));
if (count($errors) !== 0) {
    print sprintf('%s%s', implode(PHP_EOL, array_keys($errors)), PHP_EOL)
    and exit(1);
}

exit(0);
